name: Pushing Images to ECR

on:
  push:
    branches:
      - test

env:
  IMAGE_TAG: (${{ github.sha }})

jobs:
  build-push:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get Short SHA
        run: |
          SHORT_SHA=$(git log -n1 --format=format:"%H:%h" | cut -d: -f2)
          echo "::set-env name=SHORT_SHA::$SHORT_SHA"

      - name: Build and Tag Vote Docker Image
        id: build-image-vote
        uses: docker/build-push-action@v2
        with:
          context:  ./callback-service
          push: false
          tags: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:callback-${{ SHORT_SHA }}

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:callback-${{ SHORT_SHA }}
          echo "Push successful"

      - name: Build and Tag Vote Docker Image
        id: build-image-worker
        uses: docker/build-push-action@v2
        with:
          context: ./NameValidation
          push: false
          tags: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:NameVali-${{ env.IMAGE_TAG }}

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:NameVali-${{ env.IMAGE_TAG }}
          echo "Push successful"

      - name: Build and Tag Result Docker Image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: ./ussd-gateway-service
          push: false
          tags: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:ussd-gateway-${{ env.IMAGE_TAG }}

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:ussd-gateway-${{ env.IMAGE_TAG }}
          echo "Push successful"